### ISSUE TITLE
Deliver Project Proposal 

### ISSUE THREAD

**Issue by Cors00** [i-on-project/kafka-web-gateway#2]
Write and deliver the project proposal until 2023-03-20.

**Comment by pmhsfelix** [comment]
Proposed structure:
- The context
    - What is the Kafka system, how it is used, and some usage examples.
    - Web architecture and protocols - HTTP, SSE, WebSockets.
- The problem.
    - ...
- The solution.
    - ...
- Brief overview of the solution architecture.
- Challenges and risks.

The project proposal should be a good opportunity for some deep-thought about the above items.

**Comment by mjbmarques** [comment]
Submitted in 2023-03-20.
