### ISSUE TITLE
Kafka Docker Image

### ISSUE THREAD

**Issue by mjbmarques** [i-on-project/kafka-web-gateway#4]
Create a Kafka docker image from scratch.
- [ ] Kafka image Dockerfile
- [ ] docker-compose
- [ ] Have at least 2 clusters

**Comment by mjbmarques** [comment]
The image creation was originating problems in the building phase, so in the meanwhile, to not waste time and be able to test the other modules, an official Ubuntu Kafka docker image is being used alongside a Zookeeper image.

**Comment by Cors00** [comment]
Added a docker compose with a cluster composed of 3 bitnami/zookeeper containers and 3 bitnami/kafka containers, each kafka broker exposing port 29092, 39092, 49092 respectively.
